vocab_size: 49152
max_position_embeddings: 8192
hidden_size: 576
intermediate_size: 1536
num_hidden_layers: 30
num_attention_heads: 9
num_key_value_heads: 3
hidden_act: silu
initializer_range: 0.041666666666666664
rms_norm_eps: 1.0e-05
pretraining_tp: 1
use_cache: true
rope_theta: 100000
rope_scaling: null
attention_bias: false
attention_dropout: 0.0
mlp_bias: false
head_dim: 64
return_dict: true
output_hidden_states: false
torchscript: false
dtype: bfloat16
pruned_heads: {}
tie_word_embeddings: true
chunk_size_feed_forward: 0
is_encoder_decoder: false
is_decoder: false
cross_attention_hidden_size: null
add_cross_attention: false
tie_encoder_decoder: false
architectures:
- LlamaForCausalLM
finetuning_task: null
id2label:
  0: LABEL_0
  1: LABEL_1
label2id:
  LABEL_0: 0
  LABEL_1: 1
task_specific_params: null
problem_type: null
tokenizer_class: null
prefix: null
bos_token_id: 0
pad_token_id: null
eos_token_id: 0
sep_token_id: null
decoder_start_token_id: null
max_length: 20
min_length: 0
do_sample: false
early_stopping: false
num_beams: 1
temperature: 1.0
top_k: 50
top_p: 1.0
typical_p: 1.0
repetition_penalty: 1.0
length_penalty: 1.0
no_repeat_ngram_size: 0
encoder_no_repeat_ngram_size: 0
bad_words_ids: null
num_return_sequences: 1
output_scores: false
return_dict_in_generate: false
forced_bos_token_id: null
forced_eos_token_id: null
remove_invalid_values: false
exponential_decay_length_penalty: null
suppress_tokens: null
begin_suppress_tokens: null
num_beam_groups: 1
diversity_penalty: 0.0
_name_or_path: HuggingFaceTB/SmolLM2-135M
transformers_version: 4.57.3
is_llama_config: true
model_type: llama
rope_interleaved: false
tf_legacy_loss: false
use_bfloat16: false
output_attentions: false
